---
title: "Vignette Title"
author:
- name: Shouguo Gao
  affiliation: NHLBI/NIH
- name: Neal S. Young
  affiliation: NHLBI/NIH
  email: shouguo.gao@nih.gov
output:
  BiocStyle::html_document
abstract: |
  Description of your vignette
vignette: |
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette shows an example of applying pathway level to infer cell-type-specific co-expression networks and extracting co-expressed gene modules that are enriched for biological functions in cell types.

```{r eval = TRUE}
rm(list = ls())
source("../R/functions.R")
source("../R/networkFunctions.R")
networks<-GOSimPPI()
load("../data/ChuDataset.RData")
```
#Let us load the data

```{r eval = TRUE}
Chu3 <- log2(Chu3+1.1)
integ.l <- DoIntegPPI(exp.m = Chu3, ppiA.m = networks$PPI)
maxSR<-CompMaxSR(integ.l)
result<-CompSRanaPRL(1, exp.m = integ.l$expMC, adj.m = integ.l$adjMC, local = FALSE, maxSR = maxSR)
###Weighted with GO similarity
integ.l$adjMC<-integ.l$adjMC * (1+networks$GOSim[rownames(integ.l$adjMC), colnames(integ.l$adjMC)])/2
```
#Calculate the scores
```{r eval = TRUE}
head(integ.l$adjMC[,1:5])
sr.o <- CompSRana(integ.l, local = FALSE, mc.cores = 1)  #4)
sr.o.normal <- CompSRana(integ.l, local = TRUE, mc.cores = 1)  #4)
save(sr.o, sr.o.normal, file = "Chu3_results_PPIWithGOSimilarity.RData")
```
#Let us check the scores
```{r eval = TRUE}
#Chu3 bulkRNA Human 19 Pl >NonPl hESCs to MPs 7 versus 12 [38]
library(pROC);library(readxl)
sheet_names <- excel_sheets("samplesInformation.xlsx")           # Get sheet names
list_all <- lapply(sheet_names, function(x){as.data.frame(read_excel("samplesInformation.xlsx", sheet = x)) } )
names(list_all) <- sheet_names                         # Rename list elements
load("Chu3_results_PPIWithGOSimilarity.RData")
phenotype<-list_all[["GSE75748_bulk_cell_type_ec"]];phenotype$SR<-sr.o$SR
phenotype$compare<-"PI"; phenotype$compare[!phenotype$type %in% c("H1", "H9")]<-"nonPI" 
ttest<-t.test(phenotype$SR[phenotype$compare=="PI"], phenotype$SR[!phenotype$compare=="PI"])
roc1<-roc(phenotype$compare, phenotype$SR);

```
#Plot the boxplot
```{r, fig.width = 20, fig.height = 8}
  boxplot(SR~compare, data = phenotype, main = paste0("P value:", round(ttest$p.value, 8)))
```
#Plot ROC
```{r, fig.width = 20, fig.height = 8}
plot(roc1, main = paste0("AUC:", roc1$auc))
```
